### ISSUE TITLE
Close definition popup if the reader clicks on the audiobook icon on reading screen

### ISSUE THREAD

**Issue by cmurray191** [Fattimo/hear-a-tale-awakening_JIB1339#166] opened 2022-04-04 00:06 UTC
If the popup is open, it should close if the reader clicks on the audiobook icon to begin playing the book audio. When the popup closes, the audio for the definition should stop playing as well.

**Comment by Fattimo** [comment] 2022-04-10 01:49
duplicate of #166

**Comment by Fattimo** [comment] 2022-04-10 01:51
just delete the second sentence

**Closed** 2022-04-10 17:26 UTC
Labels: Engineering
